/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.restaurante.Vistas;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Alumno
 */
public class MesasView extends javax.swing.JInternalFrame {

    /**
     * Creates new form MesasView
     */
    public MesasView() {
        initComponents();
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        estilos();
    }
    private void estilos(){
        jPanel1.setBackground(new Color(35,34,36,210));
        jlTransparenciaCarga.setBackground(new Color(35,34,36,160));
        jlTransparenciaModificar.setBackground(new Color(35,34,36,160));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTituloIntereno = new javax.swing.JLabel();
        jlCerrar = new javax.swing.JLabel();
        jlTransparenciaCarga = new javax.swing.JLabel();
        jlTransparenciaModificar = new javax.swing.JLabel();
        jlFondoImagen = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(540, 580));
        setPreferredSize(new java.awt.Dimension(540, 590));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTituloIntereno.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlTituloIntereno.setText("Carga y Modificacion de Mesas");
        jPanel1.add(jlTituloIntereno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 40));

        jlCerrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCerrar.setText("Exit");
        jlCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCerrarMouseExited(evt);
            }
        });
        jPanel1.add(jlCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 50, 30));

        jlTransparenciaCarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTransparenciaCarga.setOpaque(true);
        jPanel1.add(jlTransparenciaCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 46, 500, 110));

        jlTransparenciaModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTransparenciaModificar.setOpaque(true);
        jPanel1.add(jlTransparenciaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 166, 500, 360));

        jlFondoImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFondoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/restaurante/resources/imagenes/FondoInternalFrames.jpg"))); // NOI18N
        jPanel1.add(jlFondoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCerrarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jlCerrarMouseClicked

    private void jlCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCerrarMouseEntered
        // TODO add your handling code here:
        jlCerrar.setForeground(Color.gray);
    }//GEN-LAST:event_jlCerrarMouseEntered

    private void jlCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCerrarMouseExited
        // TODO add your handling code here:
        jlCerrar.setForeground(Color.white);
    }//GEN-LAST:event_jlCerrarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlCerrar;
    private javax.swing.JLabel jlFondoImagen;
    private javax.swing.JLabel jlTituloIntereno;
    private javax.swing.JLabel jlTransparenciaCarga;
    private javax.swing.JLabel jlTransparenciaModificar;
    // End of variables declaration//GEN-END:variables
    
}
