/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.restaurante.Vistas;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import proyecto.restaurante.Control.*;
import proyecto.restaurante.Entidades.*;

/**
 *
 * @author Alumno
 */
public class IngresosView extends javax.swing.JInternalFrame {
    private static Mesero mesero;
    private static Mesa mesa;
    private static PedidoData pd;
    private static MeseroData md;
    DefaultTableModel dtm=new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    /**
     * Creates new form IngresosView
     */
    public IngresosView() {
        initComponents();
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        estilos();
        jcbMeseros.setEnabled(false);
        armarCabecera();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo = new javax.swing.JPanel();
        jlTituloIngresos = new javax.swing.JLabel();
        jlMesero = new javax.swing.JLabel();
        jcbMeseros = new javax.swing.JComboBox<>();
        jlDetalles = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaDetalles = new javax.swing.JTable();
        jbListarTodo = new javax.swing.JButton();
        jlFondoTrasparente1 = new javax.swing.JLabel();
        jlCerrar = new javax.swing.JLabel();
        jlFondoImage = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        setPreferredSize(new java.awt.Dimension(540, 590));

        jpFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTituloIngresos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlTituloIngresos.setForeground(new java.awt.Color(255, 255, 255));
        jlTituloIngresos.setText("Administración de Ingresos");
        jpFondo.add(jlTituloIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 40));

        jlMesero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlMesero.setForeground(new java.awt.Color(255, 255, 255));
        jlMesero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMesero.setText("Mesero:");
        jpFondo.add(jlMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jcbMeseros.setOpaque(false);
        jcbMeseros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbMeserosMouseClicked(evt);
            }
        });
        jcbMeseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMeserosActionPerformed(evt);
            }
        });
        jpFondo.add(jcbMeseros, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 180, -1));

        jlDetalles.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlDetalles.setForeground(new java.awt.Color(255, 255, 255));
        jlDetalles.setText("Detalles:");
        jpFondo.add(jlDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jtListaDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtListaDetalles);

        jpFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 120));

        jbListarTodo.setText("Listar Todo");
        jbListarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarTodoActionPerformed(evt);
            }
        });
        jpFondo.add(jbListarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jlFondoTrasparente1.setOpaque(true);
        jpFondo.add(jlFondoTrasparente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 100, 500, 360));

        jlCerrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jlCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCerrar.setText("Exit");
        jlCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCerrarMouseClicked(evt);
            }
        });
        jpFondo.add(jlCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 50, 30));

        jlFondoImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFondoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/restaurante/resources/imagenes/FondoInternalFrames.jpg"))); // NOI18N
        jpFondo.add(jlFondoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jlCerrarMouseClicked

    private void jcbMeserosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbMeserosMouseClicked
        if(!jcbMeseros.isEnabled()){
            jcbMeseros.setEnabled(true);
            jcbMeseros.setFocusable(true);
            cargarBox();
        }
    }//GEN-LAST:event_jcbMeserosMouseClicked

    private void jbListarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarTodoActionPerformed
        jcbMeseros.removeAllItems();
        jcbMeseros.setEnabled(false);
//        cargarTabla();
        borrarFila();
    }//GEN-LAST:event_jbListarTodoActionPerformed

    private void jcbMeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMeserosActionPerformed
        pd=new PedidoData();
        borrarFila();
        mesero=(Mesero)jcbMeseros.getSelectedItem();
        for(Pedido p:pd.obtenerMesasOcupadasPorMesero(mesero.getIdMesero())){
            dtm.addRow(new Object[]{
                p.getMesero().getNombre(),
                p.getMesero().getApellido(),
                p.getMesa().getIdMesa(),
                p.getImporte()
            });
        }
    }//GEN-LAST:event_jcbMeserosActionPerformed

    private void estilos(){
        jlFondoTrasparente1.setBackground(new Color(35,34,36,160));
    }

    private void cargarTabla(){
        pd=new PedidoData();
        //6688223
        borrarFila();
        for(Pedido p:pd.listarPedidos()){
            dtm.addRow(new Object[]{
                p.getMesero().getNombre(),
                p.getMesero().getApellido(),
                p.getMesa().getIdMesa(),
                p.getImporte()
            });
        }
    }
    
    private void cargarBox(){
        jcbMeseros.removeAllItems();
        md=new MeseroData();
        for(Mesero m:md.ListarMeseros()){
            jcbMeseros.addItem(m);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbListarTodo;
    private javax.swing.JComboBox<Mesero> jcbMeseros;
    private javax.swing.JLabel jlCerrar;
    private javax.swing.JLabel jlDetalles;
    private javax.swing.JLabel jlFondoImage;
    private javax.swing.JLabel jlFondoTrasparente1;
    private javax.swing.JLabel jlMesero;
    private javax.swing.JLabel jlTituloIngresos;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JTable jtListaDetalles;
    // End of variables declaration//GEN-END:variables

    private void borrarFila(){
        int f=jtListaDetalles.getRowCount()-1;
        for(;f>=0;f--){
            dtm.removeRow(f);
        }
    }
    private void armarCabecera(){
        dtm.addColumn("Mesero/s");
        dtm.addColumn("Apellido");
        dtm.addColumn("Mesa/s");
        dtm.addColumn("Importe");
        jtListaDetalles.setModel(dtm);
    }
}
